#!/usr/bin/env python3
"""Build a Markdown coverage report from the AIUC-1 mapping CSV."""

import csv
import sys
from pathlib import Path

# Paths are anchored to this file so the script runs from any working directory.
ROOT = Path(__file__).resolve().parent
MAPPING_PATH = ROOT / "data" / "mapping.csv"
REPORT_PATH = ROOT / "reports" / "coverage_report.md"

REQUIRED_COLUMNS = [
    "aiuc1_id",
    "aiuc1_domain",
    "aiuc1_requirement_summary",
    "iso42001_refs",
    "coverage",
    "notes",
]
VALID_COVERAGE = ("full", "partial", "none")
# Shown in the gap list: anything an ISO/IEC 42001 certification does not fully cover.
GAP_LEVELS = ("partial", "none")


def read_mapping(path):
    """Load mapping rows. Returns (rows, error). error is a string when the file cannot be used."""
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            return None, f"error: {path.name} is empty"

        fieldnames = [(name or "").strip() for name in reader.fieldnames]
        missing = [column for column in REQUIRED_COLUMNS if column not in fieldnames]
        if missing:
            return None, "error: missing required columns: " + ", ".join(missing)

        rows = []
        for line_number, raw in enumerate(reader, start=2):
            row = {
                (key or "").strip(): (value or "").strip()
                for key, value in raw.items()
                if key
            }
            # Ignore blank lines so a trailing newline is not reported as a bad row.
            if all(not row.get(column) for column in REQUIRED_COLUMNS):
                continue
            row["_line"] = line_number
            rows.append(row)
        return rows, None


def check_rows(rows):
    """Return valid rows, validation errors, and flags for covered rows with no clause reference."""
    valid = []
    errors = []
    flags = []
    allowed = ", ".join(VALID_COVERAGE)

    for row in rows:
        line = row["_line"]
        label = row["aiuc1_id"] or "(no id)"
        coverage = row["coverage"]

        if coverage not in VALID_COVERAGE:
            errors.append(
                f"error: line {line} ({label}): coverage {coverage!r} is invalid; "
                f"expected one of: {allowed}"
            )
            continue

        # full/partial claims need a clause reference; none may leave the column blank.
        if coverage in ("full", "partial") and not row["iso42001_refs"]:
            flags.append(
                f"warning: line {line} ({label}): coverage is {coverage!r} "
                "but iso42001_refs is empty"
            )
        valid.append(row)

    return valid, errors, flags


def _cell(value):
    """Keep one Markdown table cell on a single line."""
    text = (value or "").replace("|", "\\|").replace("\n", " ").strip()
    return text if text else "—"


def _percent(count, total):
    if total == 0:
        return "0.0%"
    return f"{(100.0 * count / total):.1f}%"


def build_report(valid, errors, flags):
    """Render the summary table and the gap list."""
    total = len(valid)
    counts = {
        level: sum(1 for row in valid if row["coverage"] == level)
        for level in VALID_COVERAGE
    }

    lines = [
        "# AIUC-1 coverage against ISO/IEC 42001",
        "",
        "Generated by `coverage_report.py` from `data/mapping.csv`.",
        "Version 0.1 covers the Data & Privacy domain only.",
        "The example rows are placeholders.",
        "",
        "## Summary",
        "",
        "| Coverage | Count | Percentage |",
        "| --- | ---: | ---: |",
    ]
    for level in VALID_COVERAGE:
        lines.append(f"| {level} | {counts[level]} | {_percent(counts[level], total)} |")
    total_pct = "100%" if total else "0.0%"
    lines.append(f"| **Total** | **{total}** | **{total_pct}** |")
    lines.append("")

    if errors or flags:
        lines.extend(["## Data quality", ""])
        if errors:
            lines.append("These rows were excluded from the summary and the gap list.")
            lines.append("")
            lines.extend(f"- {message}" for message in errors)
            lines.append("")
        if flags:
            lines.append(
                "These rows claim coverage but do not cite an ISO/IEC 42001 clause reference."
            )
            lines.append("")
            lines.extend(f"- {message}" for message in flags)
            lines.append("")

    gaps = [row for row in valid if row["coverage"] in GAP_LEVELS]
    lines.extend(
        [
            "## Gap list",
            "",
            "Every requirement mapped as `partial` or `none`.",
            "",
        ]
    )
    if not gaps:
        lines.extend(["No gaps in the current mapping.", ""])
    else:
        lines.extend(
            [
                "| AIUC-1 ID | Domain | Requirement summary | Coverage | ISO/IEC 42001 refs | Notes |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in gaps:
            lines.append(
                "| {id} | {domain} | {summary} | {coverage} | {refs} | {notes} |".format(
                    id=_cell(row["aiuc1_id"]),
                    domain=_cell(row["aiuc1_domain"]),
                    summary=_cell(row["aiuc1_requirement_summary"]),
                    coverage=_cell(row["coverage"]),
                    refs=_cell(row["iso42001_refs"]),
                    notes=_cell(row["notes"]),
                )
            )
        lines.append("")

    lines.extend(
        [
            "ISO/IEC 42001 text is copyrighted. This report cites clause references and original summaries only.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    if not MAPPING_PATH.is_file():
        print(f"error: mapping file not found: {MAPPING_PATH}", file=sys.stderr)
        return 1

    rows, error = read_mapping(MAPPING_PATH)
    if error:
        print(error, file=sys.stderr)
        return 1

    valid, errors, flags = check_rows(rows)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(valid, errors, flags), encoding="utf-8")

    for message in errors:
        print(message, file=sys.stderr)
    for message in flags:
        print(message, file=sys.stderr)

    print(f"Read {len(rows)} row(s) from data/mapping.csv")
    for level in VALID_COVERAGE:
        count = sum(1 for row in valid if row["coverage"] == level)
        print(f"  {level:<7} {count:>3}  ({_percent(count, len(valid))})")
    gap_count = sum(1 for row in valid if row["coverage"] in GAP_LEVELS)
    print(f"Gaps (partial or none): {gap_count}")
    print("Wrote reports/coverage_report.md")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
