#!/usr/bin/env python3
"""Build a Markdown coverage report from the AIUC-1 to NIST AI RMF mapping CSV."""

import csv
import sys
from pathlib import Path

# Paths are anchored to this file so the script runs from any working directory.
ROOT = Path(__file__).resolve().parent
MAPPING_PATH = ROOT / "data" / "mapping.csv"
REPORT_PATH = ROOT / "reports" / "coverage_report.md"

REQUIRED_COLUMNS = [
    "aiuc1_id",
    "aiuc1_requirement_summary",
    "ai_rmf_refs",
    "coverage",
    "iso42001_refs_via_nist_crosswalk",
    "official_aiuc1_crosswalk_rating",
    "notes",
]
VALID_COVERAGE = ("full", "partial", "none")
# Shown in the gap list: anything this mapping does not fully cover in the NIST AI RMF.
GAP_LEVELS = ("partial", "none")


def read_mapping(path):
    """Load mapping rows. Returns (rows, error). error is a string when the file cannot be used."""
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames:
            return None, f"error: {path.name} is empty"

        fieldnames = [(name or "").strip() for name in reader.fieldnames]
        missing = [column for column in REQUIRED_COLUMNS if column not in fieldnames]
        if missing:
            return None, "error: missing required columns: " + ", ".join(missing)

        rows = []
        for line_number, raw in enumerate(reader, start=2):
            row = {
                (key or "").strip(): (value or "").strip()
                for key, value in raw.items()
                if key
            }
            # Ignore blank lines so a trailing newline is not reported as a bad row.
            if all(not row.get(column) for column in REQUIRED_COLUMNS):
                continue
            row["_line"] = line_number
            rows.append(row)
        return rows, None


def check_rows(rows):
    """Return valid rows, validation errors, and flags for covered rows with no AI RMF reference."""
    valid = []
    errors = []
    flags = []
    allowed = ", ".join(VALID_COVERAGE)

    for row in rows:
        line = row["_line"]
        label = row["aiuc1_id"] or "(no id)"
        coverage = row["coverage"]
        official = row["official_aiuc1_crosswalk_rating"]

        if coverage not in VALID_COVERAGE:
            errors.append(
                f"error: line {line} ({label}): coverage {coverage!r} is invalid; "
                f"expected one of: {allowed}"
            )
            continue

        # A blank official rating is allowed and is reported as a difference later.
        if official and official not in VALID_COVERAGE:
            errors.append(
                f"error: line {line} ({label}): official_aiuc1_crosswalk_rating {official!r} "
                f"is invalid; expected one of: {allowed}"
            )
            continue

        # full/partial claims need an AI RMF reference; none may leave that column blank.
        if coverage in ("full", "partial") and not row["ai_rmf_refs"]:
            flags.append(
                f"warning: line {line} ({label}): coverage is {coverage!r} "
                "but ai_rmf_refs is empty"
            )
        valid.append(row)

    return valid, errors, flags


def rating_differences(rows):
    """Rows whose coverage rating is not the official AIUC-1 crosswalk rating."""
    return [
        row
        for row in rows
        if row["coverage"] != row["official_aiuc1_crosswalk_rating"]
    ]


def _cell(value):
    """Keep one Markdown table cell on a single line."""
    text = (value or "").replace("|", "\\|").replace("\n", " ").strip()
    return text if text else "—"


def _percent(count, total):
    if total == 0:
        return "0.0%"
    return f"{(100.0 * count / total):.1f}%"


def _difference_line(row):
    official = row["official_aiuc1_crosswalk_rating"] or "(blank)"
    label = row["aiuc1_id"] or "(no id)"
    return (
        f"line {row['_line']} ({label}): coverage {row['coverage']!r} "
        f"differs from official_aiuc1_crosswalk_rating {official!r}"
    )


def build_report(valid, errors, flags):
    """Render the summary, the gap list, and rating differences."""
    total = len(valid)
    counts = {
        level: sum(1 for row in valid if row["coverage"] == level)
        for level in VALID_COVERAGE
    }
    differences = rating_differences(valid)

    lines = [
        "# AIUC-1 coverage against the NIST AI RMF",
        "",
        "Generated by `coverage_report.py` from `data/mapping.csv`.",
        "ISO/IEC 42001 references come from NIST's published AI RMF to ISO/IEC 42001 crosswalk, which was built against the FDIS draft.",
        "The example rows are placeholders.",
        "",
        "## Summary",
        "",
        "| Coverage | Count | Percentage |",
        "| --- | ---: | ---: |",
    ]
    for level in VALID_COVERAGE:
        lines.append(f"| {level} | {counts[level]} | {_percent(counts[level], total)} |")
    total_pct = "100%" if total else "0.0%"
    lines.append(f"| **Total** | **{total}** | **{total_pct}** |")
    lines.append("")

    if errors or flags:
        lines.extend(["## Data quality", ""])
        if errors:
            lines.append("These rows were excluded from the summary, the gap list, and the rating differences.")
            lines.append("")
            lines.extend(f"- {message}" for message in errors)
            lines.append("")
        if flags:
            lines.append(
                "These rows claim coverage but do not cite a NIST AI RMF reference."
            )
            lines.append("")
            lines.extend(f"- {message}" for message in flags)
            lines.append("")

    gaps = [row for row in valid if row["coverage"] in GAP_LEVELS]
    lines.extend(
        [
            "## Gap list",
            "",
            "Every requirement mapped as `partial` or `none` against the NIST AI RMF.",
            "",
        ]
    )
    if not gaps:
        lines.extend(["No gaps in the current mapping.", ""])
    else:
        lines.extend(
            [
                "| AIUC-1 ID | Requirement summary | Coverage | AI RMF refs | ISO/IEC 42001 refs via NIST crosswalk | Official rating | Notes |",
                "| --- | --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in gaps:
            lines.append(
                "| {id} | {summary} | {coverage} | {rmf} | {iso} | {official} | {notes} |".format(
                    id=_cell(row["aiuc1_id"]),
                    summary=_cell(row["aiuc1_requirement_summary"]),
                    coverage=_cell(row["coverage"]),
                    rmf=_cell(row["ai_rmf_refs"]),
                    iso=_cell(row["iso42001_refs_via_nist_crosswalk"]),
                    official=_cell(row["official_aiuc1_crosswalk_rating"]),
                    notes=_cell(row["notes"]),
                )
            )
        lines.append("")

    lines.extend(
        [
            "## Rating differences",
            "",
            "Rows where `coverage` differs from `official_aiuc1_crosswalk_rating`.",
            "A blank official rating is treated as different from any coverage value.",
            "",
        ]
    )
    if not differences:
        lines.extend(["No coverage ratings differ from the official AIUC-1 crosswalk rating.", ""])
    else:
        lines.extend(
            [
                "| AIUC-1 ID | Requirement summary | Coverage | Official AIUC-1 crosswalk rating | AI RMF refs | Notes |",
                "| --- | --- | --- | --- | --- | --- |",
            ]
        )
        for row in differences:
            lines.append(
                "| {id} | {summary} | {coverage} | {official} | {rmf} | {notes} |".format(
                    id=_cell(row["aiuc1_id"]),
                    summary=_cell(row["aiuc1_requirement_summary"]),
                    coverage=_cell(row["coverage"]),
                    official=_cell(row["official_aiuc1_crosswalk_rating"]),
                    rmf=_cell(row["ai_rmf_refs"]),
                    notes=_cell(row["notes"]),
                )
            )
        lines.append("")

    lines.extend(
        [
            "No ISO/IEC 42001 text is reproduced. ISO references are clause identifiers taken from NIST's crosswalk.",
            "",
        ]
    )
    return "\n".join(lines)


def main():
    if not MAPPING_PATH.is_file():
        print(f"error: mapping file not found: {MAPPING_PATH}", file=sys.stderr)
        return 1

    rows, error = read_mapping(MAPPING_PATH)
    if error:
        print(error, file=sys.stderr)
        return 1

    valid, errors, flags = check_rows(rows)
    differences = rating_differences(valid)
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(build_report(valid, errors, flags), encoding="utf-8")

    for message in errors:
        print(message, file=sys.stderr)
    for message in flags:
        print(message, file=sys.stderr)

    print(f"Read {len(rows)} row(s) from data/mapping.csv")
    for level in VALID_COVERAGE:
        count = sum(1 for row in valid if row["coverage"] == level)
        print(f"  {level:<7} {count:>3}  ({_percent(count, len(valid))})")
    gap_count = sum(1 for row in valid if row["coverage"] in GAP_LEVELS)
    print(f"Gaps (partial or none): {gap_count}")
    print(f"Rating differences: {len(differences)}")
    for row in differences:
        print(f"  {_difference_line(row)}")
    print("Wrote reports/coverage_report.md")
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main())
